application: longwargame
version: 1
runtime: go
api_version: go1

handlers:
- url: /(.*\.(js|css|png))
  static_files: static/\1
  upload: static/(.*\.(js|css|png))

- url: /rnd
  script: _go_app

- url: /
  script: _go_app
